### PR TITLE
Phone input

### PR DESCRIPTION
**Pull request by mathzdev**

### CODE REVIEW

**Review by ChristopherTrimboli — CHANGES_REQUESTED** [review]
Some issue with the width, it cuts off the text but the form keeps going: 

image

Should not be able to enter letters:

image

When select a country, it should populate the area code: 
For example, Brazil is +55 but input is showing 11

image

**Review by ChristopherTrimboli — COMMENTED** [review]
isError should be constant, not just hover

**Comment by mathzdev** [comment]
> isError should be constant, not just hover

solved

**Review by ChristopherTrimboli — APPROVED** [review]
sweet!

**Pull request merged**
